version: '3'

services:
  concourse-db:
    image: postgres
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      PGDATA: /database

  concourse-web:
    image: concourse/concourse
    command: web
    privileged: true
    depends_on: [concourse-db]
    volumes: ["./keys/web:/concourse-keys"]
    ports: ["8080:8080","2222:2222"]
    environment:
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER:
      CONCOURSE_POSTGRES_PASSWORD:
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test

  concourse-worker:
    image: concourse/concourse
    command: worker
    privileged: true
    depends_on: [concourse-web]
    volumes: ["./keys/worker:/concourse-keys"]
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222